//===========================================================================//
// Copyright (C) Microsoft Corporation. All rights reserved.                 //
//===========================================================================//

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define MBOK                            1
#define IDC_CHOOSE_UNIT_USING_POINTER_BUTTON 3
#define IDC_ADD_POSSIBILITY             3
#define IDSAVE                          3
#define IDC_REMOVE_POSSIBILITY          4
#define IDLOAD                          4
#define ID_ALIGNMENT_TEAM1              50
#define ID_ALIGNMENT_ENEMY              51
#define ID_ALIGNMENT_NEUTRAL            52
#define ID_ALIGNMENT_TEAM4              53
#define ID_ALIGNMENT_TEAM5              54
#define ID_ALIGNMENT_TEAM6              55
#define ID_ALIGNMENT_TEAM7              56
#define ID_ALIGNMENT_TEAM8              57
#define ID_ALIGNMENT_TRUENEUTRAL        58
#define IDD_FILEOPEN                    102
#define IDR_EDITOR_MENU                 103
#define IDD_TERRAINS                    104
#define IDD_HEIGHT_DLG                  105
#define IDD_LIGHT                       106
#define IDD_WAVES                       110
#define IDD_VALUE                       111
#define IDD_OBJECTIVES                  114
#define IDD_OBJECTIVE                   116
#define IDB_BITMAP1                     117
#define IDC_MC2ARROW                    118
#define IDC_LINK                        119
#define IDC_UNLINK                      120
#define IDC_UP                          121
#define IDC_HILLS                       122
#define IDC_HAND                        123
#define IDC_PAINT                       124
#define IDC_ERASER                      125
#define IDC_FLATTEN                     126
#define IDC_HAMMER                      127
#define IDC_WRENCH                      128
#define IDI_ICON1                       128
#define IDC_TARGET                      129
#define IDC_DROPZONE                    130
#define IDD_UNITSETTINGS                131
#define IDD_CHOOSE_UNIT                 132
#define IDR_POPUP                       133
#define IDD_FOG                         133
#define IDD_CHOOSE_BUILDING             134
#define IDD_TACMAP                      135
#define IDD_TARGET_AREA                 136
#define IDD_POINTER_SELECT_OBJECT       137
#define IDR_ACCELERATOR1                139
#define IDD_BUILDINGSETTINGS            140
#define IDD_MISSION_SETTINGS            143
#define IDD_PLAYER_SETTINGS             144
#define IDD_SELECT_TERRAIN_TYPE         146
#define IDD_TEXT_MESSAGE                148
#define IDD_RESOURCE_STRING_SELECTION   149
#define IDD_FRACTAL                     151
#define IDD_FOREST_DLG                  152
#define IDD_FOREST_LIST                 153
#define IDD_MAPSIZE                     156
#define IDD_TILING_FACTORS_DIALOG       158
#define IDD_FLAG_IS_SET_DIALOG          159
#define IDD_USER_TEXT_EDIT_DIALOG       161
#define IDD_VIEW_CONDITION_OR_ACTION    162
#define IDD_SELECT_SLOPE_DIALOG         163
#define IDD_PROMPT_USER_TO_SAVE_DIALOG  164
#define IDD_NEW_SINGLEPLAYER            206
#define IDD_CAMPAIGN                    229
#define IDD_GROUP                       230
#define IDD_MISSION_DIALOG              232
#define IDC_LIGHTCOLOR                  995
#define IDC_AMBIENT                     996
#define IDC_LIGHTCOLOR2                 997
#define IDC_TERRAIN_SHADOW_COLOR        997
#define IDC_AMBIENT2                    998
#define IDC_SUNSETCOLOR                 999
#define IDC_MAX                         1007
#define IDC_PITCH                       1009
#define IDC_FILEOPEN_FILELIST           1010
#define IDC_RED1                        1010
#define IDC_PITCH2                      1010
#define IDC_FILEOPEN_EDITBOX            1011
#define IDC_GREEN1                      1011
#define IDC_MIN                         1012
#define IDC_BLUE1                       1012
#define IDC_RED2                        1013
#define IDC_TERRAINS                    1014
#define IDC_GREEN2                      1014
#define IDC_BLUE2                       1015
#define IDC_AMPLITUDE                   1015
#define IDC_SOURCE_COLOR                1016
#define IDC_FREQUENCY                   1016
#define IDC_FILEOPEN_FRAME              1016
#define IDC_AMBIENT_COLOR               1017
#define IDC_ELEVATION                   1017
#define IDC_HEIGHT                      1017
#define IDC_YAW                         1018
#define IDC_SHALLOW_ELEVATION           1018
#define IDC_TEXT                        1018
#define IDC_START                       1019
#define IDC_ALPHA_ELEVATION             1019
#define IDC_YAW2                        1019
#define IDC_INITIAL_PITCH               1019
#define IDC_END                         1020
#define IDC_ALPHA_SHALLOW               1020
#define IDC_ALPHA_MIDDLE                1021
#define IDC_ALPHA_DEEP                  1022
#define IDC_OBJECTIVES_LIST             1022
#define IDC_OBJECTIVES_ADD_BUTTON       1023
#define IDC_OBJECTIVES_REMOVE_BUTTON    1024
#define IDC_OBJECTIVES                  1025
#define IDC_OBJECTIVES_EDIT_BUTTON      1025
#define IDC_OBJECTIVES_COPY_BUTTON      1026
#define IDC_OBJECTIVES_REMOVE_MOVE_UP   1027
#define IDC_OBJECTIVES_MOVE_UP_BUTTON   1027
#define IDC_OBJECTIVE_CONDITION_LIST    1028
#define IDC_OBJECTIVES_REMOVE_MOVE_DOWN 1028
#define IDC_OBJECTIVES_MOVE_DOWN_BUTTON 1028
#define IDC_OBJECTIVE_ADD_CONDITION_BUTTON 1029
#define IDC_OBJECTIVE_REMOVE_CONDITION_BUTTON 1030
#define IDC_OBJECTIVE_DESCRIPTION_EDITBOX 1031
#define IDC_OBJECTIVE_ADD_FAILURE_CONDITION_BUTTON 1031
#define IDC_OBJECTIVE_DESCRIPTION_STATIC 1032
#define IDC_OBJECTIVE_FAILURE_CONDITION_LIST 1032
#define IDC_OBJECTIVE_CONDITIONS_STATIC 1033
#define IDC_OBJECTIVE_TYPE_OF_CONDITION_COMBOBOX 1034
#define IDC_OBJECTIVE_TYPE_OF_CONDITION_STATIC 1035
#define IDC_OBJECTIVE_TYPE_OF_CONDITION_STATIC2 1036
#define IDC_OBJECTIVE_TITLE_STATIC      1037
#define IDC_OBJECTIVE_TYPE_OF_FAILURE_CONDITION_COMBOBOX 1037
#define IDC_OBJECTIVE_TITLE_EDITBOX     1038
#define IDC_OBJECTIVE_CONDITIONS_STATIC2 1038
#define IDC_OBJECTIVE_PRIORITY_STATIC   1039
#define IDC_OBJECTIVE_FAILURE_REMOVE_CONDITION_BUTTON 1040
#define IDC_OBJECTIVE_REMOVE_FAILURE_CONDITION_BUTTON 1040
#define IDC_OBJECTIVE_PRIMARY_RADIO     1042
#define IDC_OBJECTIVE_SECONDARY_RADIO   1043
#define IDC_DISTANCE_EDIT               1044
#define IDC_GROUP                       1045
#define IDC_COORDINATES_EDIT            1045
#define IDC_CHOOSE_UNIT_COMBO           1046
#define IDC_MECH                        1046
#define IDC_ALTITUDE_EDIT               1046
#define IDC_CHOOSE_UNIT_STATIC          1047
#define IDC_BASE                        1047
#define IDC_OBJECTIVE_ACTION_LIST       1047
#define IDC_BASEEDIT                    1048
#define IDC_OBJECTIVE_ADD_ACTION_BUTTON 1048
#define IDC_PILOT                       1049
#define IDC_OBJECTIVE_REMOVE_ACTION_BUTTON 1049
#define IDC_ALIGN1                      1050
#define IDC_OBJECTIVE_ACTIONS_STATIC    1050
#define IDC_AMBIENT_BUTTON              1050
#define IDC_ALIGN2                      1051
#define IDC_OBJECTIVE_TYPE_OF_ACTION_COMBOBOX 1051
#define IDC_TERRAIN_SHADOW_BUTTON       1051
#define IDC_ALIGN3                      1052
#define IDC_OBJECTIVE_TYPE_OF_ACTION_STATIC 1052
#define IDC_LIGHT_BUTTON2               1052
#define IDC_ALIGN4                      1053
#define IDC_BASE2                       1053
#define IDC_ALIGN5                      1054
#define IDC_AMBIENT_BUTTON2             1054
#define IDC_BASEEDIT2                   1054
#define IDC_HIGHLIGHT1                  1055
#define IDC_ALIGN6                      1056
#define IDC_OBJECTIVE_TYPE_OF_ACTION_STATIC2 1056
#define IDC_ALIGN7                      1057
#define IDC_OBJECTIVE_TYPE_OF_FAILURE_ACTION_COMBOBOX 1057
#define IDC_ALIGN8                      1058
#define IDC_OBJECTIVE_ADD_FAILURE_ACTION_BUTTON 1058
#define IDC_HIGHLIGHT1EDIT              1059
#define IDC_ALIGN9                      1059
#define IDC_HIGHLIGHT2                  1060
#define IDC_HIGHILIGHT2EDIT             1061
#define IDC_OBJECTIVE_ACTIONS_STATIC2   1061
#define IDC_VARIANT                     1062
#define IDC_HIGHILIGHT2EDIT2            1062
#define IDC_POSSIBILTY_EDIT             1063
#define IDC_OBJECTIVE_FAILURE_ACTION_LIST 1063
#define IDC_NUM_POSSIBILITIES_EDIT      1064
#define IDC_OBJECTIVE_REMOVE_FAILURE_ACTION_BUTTON 1064
#define IDC_CHOOSE_BUILDING_STATIC      1066
#define IDC_CHOOSE_BUILDING_COMBO       1067
#define IDC_TGA                         1068
#define IDC_TARGET_AREA_CENTER_X_EDIT   1071
#define IDC_TARGET_AREA_CENTER_Y_EDIT   1072
#define IDC_TARGET_AREA_RADIUS_EDIT     1073
#define IDC_TARGET_AREA_USING_POINTER_BUTTON 1074
#define IDC_OBJECTIVE_RESOURCE_POINTS_EDITBOX 1075
#define IDC_OBJECTIVE_RESOURCE_POINTS_STATIC 1076
#define IDC_OBJECTIVE_PREVIOUS_CHECK    1080
#define IDC_OBJECTIVE_DISPLAY_MARKER_CHECK 1081
#define IDC_OBJECTIVE_X_EDITBOX         1082
#define IDC_OBJECTIVE_Y_EDITBOX         1083
#define IDC_OBJECTIVE_MARKER_LOCATION_STATIC 1084
#define IDC_OBJECTIVE_X_STATIC          1085
#define IDC_OBJECTIVE_Y_STATIC          1086
#define IDC_POINTER_SELECT_OBJECT_STATIC 1087
#define IDC_OBJECTIVE_ALL_PREVIOUS_CHECK 1087
#define IDC_POINTER_SELECT_OBJECT_BUTTON 1088
#define IDC_CHOOSE_BUILDING_USING_POINTER_BUTTON 1089
#define IDC_POSSIBILITY_SPIN            1092
#define IDC_SQUAD_EDIT                  1095
#define IDC_OBJECTIVE_HIDDEN_TRIGGER_CHECK 1096
#define ID_NEWMISSION                   1098
#define IDC_LIGHT_BUTTON                1098
#define ID_LOAD_MISSION                 1099
#define IDC_DAYLENGTH                   1099
#define IDC_MISSION_NAME_EDIT           1099
#define IDC_AUTHOR_EDIT                 1100
#define IDC_SUNSET_BUTTON               1100
#define IDC_BLURB_EDIT                  1101
#define IDC_BLURB2_EDIT                 1102
#define IDC_MAX_TEAMS_SPIN              1103
#define IDC_MAX_TEAMS_EDIT              1104
#define IDC_TIME_LIMIT_EDIT             1105
#define IDC_MAX_PLAYERS_SPIN            1106
#define IDC_OBJECTIVES_TEAM_EDIT        1106
#define IDC_MAX_PLAYERS_EDIT            1107
#define IDC_PLAYER_SETTINGS_PLAYER_EDIT 1107
#define IDC_PLAYER_SETTINGS_DEFAULT_TEAM_COMBO 1109
#define IDC_SINGLE_PLAYER_CHECK         1110
#define IDC_INITIAL_RESOURCE_POINTS_EDIT 1111
#define IDC_CYCLE_CHECK                 1112
#define IDC_INITIAL_CBILLS_EDIT         1112
#define IDC_SELECT_TERRAIN_TYPE_LIST    1113
#define IDC_BS_X_EDIT                   1114
#define IDC_BS_Y_EDIT                   1115
#define IDC_BS_PARTID_EDIT              1116
#define IDC_FOREST_NAME                 1117
#define IDC_SCENARIO_TUNE_COMBO         1119
#define IDC_TRANSPARENCY_EDIT           1120
#define IDC_OBJECTIVE_UNHIDE_CHECK      1121
#define IDC_OBJECTIVE_ACTIVATE_ON_FLAG_CHECK 1121
#define IDC_OBJECTIVE_UNHIDE_FLAG_EDITBOX 1122
#define IDC_OBJECTIVE_ACTIVATE_FLAG_EDITBOX 1122
#define IDC_VIDEO_FILENAME_EDIT         1123
#define IDC_OBJECTIVE_RESET_STATUS_ON_FLAG_CHECK 1123
#define IDC_BROWSE_BUTTON               1124
#define IDC_OBJECTIVE_RESET_STATUS_FLAG_EDITBOX 1124
#define IDC_SELF_REPAIR1                1126
#define IDC_SELF_REPAIR2                1127
#define IDC_ENABLE_TERRAIN_SHADOW_COLOR 1128
#define IDC_RECALCULATE_TERRAIN_SHADOWS_BUTTON 1129
#define IDC_TEXT_MESSAGE                1130
#define IDC_REFRACTALIZE_TERRAIN_BUTTON 1130
#define IDC_BLURB_USE_RESOURCE_STRING_CHECK 1131
#define IDC_BLURB_SELECT_RESOURCE_STRING_BUTTON 1132
#define IDC_BLURB_EDIT_BUTTON           1132
#define IDC_BLURB_RESOURCE_STRING_EDIT  1133
#define IDC_BLURB_RESOURCE_STRING_ID_EDIT 1134
#define IDC_RESOURCE_STRING_SELECTION_COMBO 1135
#define IDC_BLURB2_USE_RESOURCE_STRING_CHECK 1135
#define IDC_BLURB2_SELECT_RESOURCE_STRING_BUTTON 1136
#define IDC_BLURB2_EDIT_BUTTON          1136
#define IDC_BLURB2_RESOURCE_STRING_EDIT 1137
#define IDC_BLURB2_RESOURCE_STRING_ID_EDIT 1138
#define IDC_NOISE                       1138
#define IDC_MISSION_NAME_USE_RESOURCE_STRING_CHECK 1139
#define IDC_THRESHOLD                   1139
#define IDC_MISSION_NAME_SELECT_RESOURCE_STRING_BUTTON 1140
#define IDC_OBJDISTANCEEDIT             1140
#define IDC_MISSION_NAME_EDIT_BUTTON    1140
#define IDC_MISSION_NAME_RESOURCE_STRING_EDIT 1141
#define IDC_SLIDER1                     1141
#define IDC_MISSION_NAME_RESOURCE_STRING_ID_EDIT 1142
#define IDC_FOREST_EDIT1                1142
#define IDC_SLIDER2                     1143
#define IDC_FOREST_EDIT2                1144
#define IDC_SLIDER3                     1145
#define IDC_FOREST_EDIT3                1146
#define IDC_SLIDER4                     1147
#define IDC_FOREST_EDIT4                1148
#define IDC_SLIDER5                     1149
#define IDC_FOREST_EDIT5                1150
#define IDC_SLIDER6                     1151
#define IDC_FOREST_EDIT6                1152
#define IDC_SLIDER7                     1153
#define IDC_FOREST_EDIT7                1154
#define IDC_SLIDER8                     1155
#define IDC_FOREST_EDIT8                1156
#define IDC_SLIDER9                     1157
#define IDC_FOREST_EDIT9                1158
#define IDC_SLIDER10                    1159
#define IDC_FOREST_EDIT10               1160
#define IDC_SLIDER11                    1161
#define IDC_FOREST_EDIT11               1162
#define IDC_SLIDER12                    1163
#define IDC_FOREST_EDIT12               1164
#define IDC_SLIDER13                    1165
#define IDC_FOREST_EDIT13               1166
#define IDC_SLIDER14                    1167
#define IDC_MECH2                       1167
#define IDC_FOREST_EDIT14               1168
#define IDC_OBJECTIVEGROUP              1168
#define IDC_SLIDER15                    1169
#define IDC_FOREST_EDIT15               1170
#define IDC_DENSITY_MAX                 1171
#define IDC_DENSITY_MIN                 1172
#define IDC_HEIGHT_MAX                  1173
#define IDC_HEIGHT_MIN                  1174
#define IDC_RANDOM                      1175
#define IDC_XLOC                        1176
#define IDC_LIST_FILES                  1177
#define IDC_NAME_EDIT                   1177
#define IDC_YLOC                        1178
#define IDC_NAME                        1178
#define IDC_LOAD                        1179
#define IDC_NUM_RP_BUILDINGS_EDIT       1179
#define IDC_RADIUS                      1180
#define IDC_NUM_RP_BUILDINGS_SPIN       1180
#define IDC_DELETE                      1181
#define IDC_DOWNLOAD_URL_EDIT           1181
#define IDC_EDIT                        1182
#define IDC_MISSION_TYPE_COMBO          1182
#define IDC_SAVE                        1183
#define IDC_RENAME                      1183
#define IDC_AIR_STRIKE_CHECK            1183
#define IDC_MINE_LAYER_CHECK            1184
#define IDC_SCOUT_COPTER_CHECK          1185
#define IDC_SENSOR_PROBE_CHECK          1186
#define IDC_UNLIMITED_AMMO_CHECK        1187
#define IDC_ALL_TECH_CHECK              1188
#define IDC_REPAIR_VEHICLE_CHECK        1190
#define IDC_SALVAGE_CRAFT_CHECK         1191
#define IDC_RESOURCE_BUILDING_CHECK     1192
#define IDC_NO_VARIANTS_CHECK           1193
#define IDC_DROP_WEIGHT_EDIT            1194
#define IDC_OBJECTIVE_TITLE_USE_RESOURCE_STRING_CHECK 1195
#define IDC_OBJECTIVE_TITLE_SELECT_RESOURCE_STRING_BUTTON 1196
#define IDC_OBJECTIVE_TITLE_EDIT_BUTTON 1196
#define IDC_OBJECTIVE_TITLE_RESOURCE_STRING_ID_EDIT 1197
#define IDC_OBJECTIVE_TITLE_RESOURCE_STRING_EDIT 1198
#define IDC_OBJECTIVE_TITLE_EDIT        1198
#define IDC_OBJECTIVE_DESCRIPTION_USE_RESOURCE_STRING_CHECK 1199
#define IDC_ARTILLERY_PIECE_CHECK       1199
#define IDC_OBJECTIVE_DESCRIPTION_SELECT_RESOURCE_STRING_BUTTON 1200
#define IDC_RPS_FOR_MECHS_CHECK         1200
#define IDC_OBJECTIVE_DESCRIPTION_EDIT_BUTTON 1200
#define IDC_OBJECTIVE_DESCRIPTION_RESOURCE_STRING_EDIT 1201
#define IDC_OBJECTIVE_DESCRIPTION_EDIT  1201
#define IDC_OBJECTIVE_DESCRIPTION_RESOURCE_STRING_ID_EDIT 1202
#define IDC_MAPSIZE                     1202
#define ID_CA_LOAD_BUTTON               1203
#define IDC_USER_TEXT_EDIT_ENTER_TEXT_BUTTON 1203
#define IDC_TILING_FACTORS_TERRAIN_DETAIL_EDIT 1207
#define IDC_TILING_FACTORS_WATER_EDIT   1208
#define IDC_FLAG_IS_SET_INDEX_EDIT      1208
#define IDC_FLAG_IS_SET_ID_EDIT         1208
#define IDC_TILING_FACTORS_WATER_DETAIL_EDIT 1209
#define IDC_FLAG_IS_SET_VALUE_COMBO     1210
#define IDC_USER_TEXT_EDIT_SELECT_RESOURCE_STRING_BUTTON 1211
#define IDC_USER_TEXT_EDIT_RESOURCE_STRING_ID_EDIT 1212
#define IDC_USER_TEXT_EDIT_EDIT         1213
#define IDC_CA_NAME_RESOURCE_STRING_ID_EDIT 1216
#define IDC_CA_NAME_EDIT                1217
#define IDC_CA_NAME_EDIT_BUTTON         1218
#define IDC_VIEW_CONDITION_OR_ACTION_EDIT 1219
#define IDC_OBJECTIVE_VIEW_CONDITION_BUTTON 1220
#define IDC_OBJECTIVE_VIEW_FAILURE_CONDITION_BUTTON 1221
#define IDC_SELECT_SLOPE_MIN_EDIT       1221
#define IDC_OBJECTIVE_VIEW_ACTION_BUTTON 1222
#define IDC_SELECT_SLOPE_MAX_EDIT       1222
#define IDC_OBJECTIVE_VIEW_FAILURE_ACTION_BUTTON 1223
#define IDC_PROMPT_USER_TO_SAVE_SAVE_BUTTON 1224
#define IDC_PROMPT_USER_TO_SAVE_SAVE_AS_BUTTON 1225
#define IDC_OBJECTIVE_CLEAR_LOGISTICS_MODEL_BUTTON 1225
#define IDC_PROMPT_USER_TO_SAVE_DONT_SAVE_BUTTON 1226
#define IDC_CA_CBILLS_EDIT              2002
#define IDC_CA_FINAL_VIDEO_EDIT         2003
#define IDC_CA_FINAL_VIDEO_BROWSE_BUTTON 2004
#define IDC_CA_GROUP_LIST               2005
#define IDC_CA_ADD_BUTTON               2006
#define IDC_CA_REMOVE_BUTTON            2007
#define IDC_CA_EDIT_BUTTON              2008
#define IDC_GR_NUM_MISSIONS_TO_COMPLETE_EDIT 2009
#define IDC_CA_MOVE_UP_BUTTON           2009
#define IDC_GR_OPERATION_FILE_BROWSE_BUTTON 2010
#define IDC_CA_MOVE_DOWN_BUTTON         2010
#define IDC_GR_OPERATION_FILE_EDIT      2011
#define IDC_GR_PREVIDEO_FILE_BROWSE_BUTTON 2012
#define IDC_GR_PREVIDEO_FILE_EDIT       2013
#define IDC_GR_VIDEO_FILE_BROWSE_BUTTON 2014
#define IDC_GR_VIDEO_FILE_EDIT          2015
#define IDC_GR_TUNE_COMBO               2016
#define IDC_GR_MISSION_LIST             2017
#define IDC_GR_ADD_BUTTON               2018
#define IDC_GR_REMOVE_BUTTON            2019
#define IDC_GR_EDIT_BUTTON              2020
#define IDC_MI_MISSION_FILE_BROWSE_BUTTON 2021
#define IDC_MI_MISSION_FILE_EDIT        2022
#define IDC_MI_PURCHASE_FILE_BROWSE_BUTTON 2023
#define IDC_MI_PURCHASE_FILE_EDIT       2024
#define IDC_MI_MANDATORY_CHECK          2025
#define IDC_MI_LOGISTICS_CHECK          2026
#define IDC_MI_PURCHASING_CHECK         2027
#define IDC_MI_SALVAGE_CHECK            2028
#define IDC_MI_PILOT_PROMOTION_CHECK    2029
#define ID_CA_SAVE_AS_BUTTON            2030
#define IDC_MI_SELECTION_SCREEN         2030
#define ID_CA_EXIT                      2031
#define IDC_GR_LABEL_EDIT               2032
#define ID_CA_SAVE_BUTTON               2032
#define IDS_SELECT_SLOPES               40001
#define ID_FOG                          40002
#define ID_FILE_SAVEAS                  40003
#define ID_FILE_EXIT                    40004
#define ID_LIGHT                        40005
#define ID_FILE_NEW2                    40006
#define ID_FILE_OPEN2                   40007
#define ID_WAVES                        40008
#define ID_FILE_ASSIGNHEIGHTMAP         40009
#define ID_DRAGSMOOTH                   40010
#define ID_DRAGNORMAL                   40011
#define ID_SMOOTH_RADIUS                40012
#define ID_OVERLAYS_DIRTROAD            40025
#define ID_OVERLAYS_PAEVEDROAD          40026
#define ID_OVERLAYS_ROUGH               40027
#define ID_OTHER_ERASE                  40028
#define ID_OTHER_SELECT                 40029
#define ID_OTHER_SELECTAREA             40030
#define ID_OTHER_FLATTEN                40031
#define ID_EDIT_UNDO2                   40032
#define ID_EDIT_REDO2                   40033
#define ID_EDIT_COPY2                   40034
#define ID_OTHER_ASSIGNHEIGHT           40035
#define ID_ALIGNMENT_PLAYER             40036
#define ID_SAVE_HEIGHT_MAP              40039
#define ID_MEASURE                      40040
#define ID_MISSION_OBJECTIVES           40041
#define ID_OTHER_DAMAGE                 40042
#define ID_OTHER_REPAIR                 40043
#define ID_OTHER_LINK                   40044
#define ID_OTHER_UNLINK                 40045
#define ID_DROPZONES_ADD                40051
#define ID_DROPZONES_VTOL               40052
#define ID_DROPZONE_ERASER              40053
#define ID_UNITSETTINGS                 40054
#define ID_VIEW_REFRESHTACMAP           40055
#define IDS_SELECT_ALTITUDE             40062
#define ID_FILE_QUICKSAVE               40063
#define IDS_MUSTBEGRAYSCALE             40064
#define IDS_NO_DROPZONE                 40065
#define ID_OVERLAYS_TWOLANEDIRTROAD     40065
#define ID_OVERLAYS_DAMAGEDROAD         40066
#define IDS_MUSTBERIGHTSIZE             40066
#define ID_OVERLAYS_RUNWAY              40067
#define IDS_MUSTHAVEHEIGHTMAP           40067
#define ID_MISSION_TIMELIMIT            40068
#define IDS_MUSTBERIGHTFORMAT           40068
#define IDS_HEIGHTMAPNOTMATCH           40069
#define ID_MISSION_SETTINGS             40070
#define IDS_BASEMUSTEXIST               40070
#define IDS_UNNAMDE_FOREST              40071
#define ID_MISSION_TEAM_TEAM1           40072
#define IDS_NO_STRUCTURES               40072
#define ID_MISSION_TEAM_TEAM2           40073
#define IDS_NO_BUILDINGS_SELECTED       40073
#define ID_MISSION_TEAM_TEAM3           40074
#define IDS_MORE_THAN_ONE_BUILDING_SELECTED 40074
#define ID_MISSION_TEAM_TEAM4           40075
#define IDS_NO_UNITS                    40075
#define ID_MISSION_TEAM_TEAM5           40076
#define IDS_NO_UNITS_SELECTED           40076
#define ID_MISSION_TEAM_TEAM6           40077
#define IDS_MORE_THAN_ONE_UNIT_SELECTED 40077
#define ID_MISSION_TEAM_TEAM7           40078
#define IDS_UNIMPLEMENTED_ACTION        40078
#define ID_MISSION_TEAM_TEAM8           40079
#define IDS_UNIMPLEMENTED_CONDITION     40079
#define ID_MISSION_PLAYER_PLAYER1       40080
#define IDS_MUST_BE_IN_SUBDIRECTORY     40080
#define ID_MISSION_PLAYER_PLAYER2       40081
#define IDS_TOO_MANY_TURRETS            40081
#define ID_MISSION_PLAYER_PLAYER3       40082
#define IDS_WRONG_SIZE_HEIGHT_MAP       40082
#define ID_MISSION_PLAYER_PLAYER4       40083
#define IDS_UNABLE_TO_DELETE_NEWMAP     40083
#define ID_MISSION_PLAYER_PLAYER5       40084
#define IDS_APPEARANCE_HEAP_EXHAUSTED   40084
#define ID_MISSION_PLAYER_PLAYER6       40085
#define IDS_DO_YOU_WANT_TO_SAVE_YOUR_CHANGES 40085
#define ID_MISSION_PLAYER_PLAYER7       40086
#define IDS_DO_YOU_WANT_TO_SAVE_THIS_MISSION 40086
#define ID_MISSION_PLAYER_PLAYER8       40087
#define IDS_PILOT_SINGLE_PLAYER_VERSION 40087
#define ID_SELECT_TERRAIN_TYPE          40088
#define IDS_PILOT_MULTIPLAYER_VERSION   40088
#define IDS_OBJECTIVES_WITH_NO_CONDITIONS 40089
#define ID_PURGE_TRANSITIONS            40090
#define IDS_COULDNT_OPEN_OPERATION_FILE 40090
#define ID_SHOW_TRANSITIONS             40091
#define IDS_NOT_A_VALID_OPERATION_FILE  40091
#define ID_OTHER_LAYMINES               40092
#define IDS_COULDNT_OPEN_PURCHASE_FILE  40092
#define IDS_NOT_A_VALID_PURCHASE_FILE   40093
#define ID_OVERLAYS_BRIDGE              40094
#define ID_OVERLAYS_DAMAGEDBRIDGE       40095
#define ID_OTHER_SELECTDETAILTEXTURE    40096
#define ID_OTHER_SELECTWATERTEXTURE     40097
#define ID_OTHER_SELECTWATERDETAILTEXTURE 40098
#define ID_SKY_SKY1                     40099
#define ID_SKY_SKY2                     40100
#define ID_SKY_SKY3                     40101
#define ID_SKY_SKY4                     40102
#define ID_SKY_SKY5                     40103
#define ID_SKY_SKY6                     40104
#define ID_SKY_SKY7                     40105
#define ID_SKY_SKY8                     40106
#define ID_SKY_SKY9                     40107
#define ID_SKY_SKY10                    40108
#define ID_SKY_SKY11                    40109
#define ID_SKY_SKY12                    40110
#define ID_OTHER_RELOADBASETEXTURE      40111
#define ID_OTHER_REFRACTALIZETERRAIN    40112
#define ID_FOREST_TOOL                  40114
#define ID_OTHER_EDITFORESTS            40115
#define ID_CAMPAIGN_EDITOR              40116
#define ID_SKY_SKY13                    40117
#define ID_SKY_SKY14                    40118
#define ID_SKY_SKY15                    40119
#define ID_SKY_SKY16                    40120
#define ID_SKY_SKY17                    40121
#define ID_SKY_SKY18                    40122
#define ID_SKY_SKY19                    40123
#define ID_SKY_SKY20                    40124
#define ID_OTHER_TEXTURETILINGFACTORS   40125
#define ID_SKY_SKY21                    40126
#define ID_OTHER_SETBASETEXTURENAME     40127
#define ID_VIEW_ORTHOGRAPHICCAMERA      40128
#define ID_VIEW_SHOWPASSABILITYMAP      40131
#define ID_TERRAINS_INVALID             59999
#define ID_TERRAINS_BLUEWATER           60000
#define ID_TERRAINS_GREENWATER          60001
#define ID_TERRAINS_MUD                 60002
#define ID_TERRAINS_DIRTY               60003
#define ID_TERRAINS_FORESTFLOOR1        60004
#define ID_TERRAINS_FORESTFLOOR2        60005
#define ID_TERRAINS_FORESTFLOOR3        60006
#define ID_TERRAINS_MUDFLATS            60007
#define ID_TERRAINS_FORESTFLOOR4        60008
#define ID_TERRAINS_MUDDYSHORE          60009
#define ID_TERRAINS_CEMENT              60010
#define ID_TERRAINS_SANDYDIRT           60011
#define ID_TERRAINS_SLIMY               60012
#define ID_TERRAINS_CEMENT2             60013
#define ID_TERRAINS_CEMENT3             60014
#define ID_TERRAINS_CEMENT4             60015
#define ID_TERRAINS_CEMENT5             60016
#define ID_TERRAINS_CEMENT6             60017
#define ID_TERRAINS_CEMENT7             60018
#define ID_TERRAINS_CEMENT8             60019
#define ID_TERRAINS_SAND1               60020
#define ID_TERRAINS_SAND2               60021
#define ID_TERRAINS_MUD1                60022
#define ID_TERRAINS_MUD2                60023
#define ID_TERRAINS_GRASSLT1            60024
#define ID_TERRAINS_GRASSLT2            60025
#define ID_TERRAINS_GRASSLT3            60026
#define ID_TERRAINS_CLIFF1              60027
#define ID_TERRAINS_CLIFF2              60028
#define ID_TERRAINS_GRASS2              60029
#define ID_TERRAINS_GRASS3              60030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         40132
#define _APS_NEXT_CONTROL_VALUE         1226
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
